# Generated by Django 5.2.17 on 2026-09-12 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='thumbnail',
            new_name='logo',
        ),
    ]
