# Generated by Django 5.2.17 on 2026-09-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_thumbnail_experience_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='logo',
            field=models.URLField(blank=True, default=''),
        ),
    ]
