# Generated by Django 5.2.17 on 2026-09-12 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_experience_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='logo',
            new_name='company_logo',
        ),
    ]
