# Generated by Django 5.2.17 on 2026-09-14 13:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_experience_options_alter_skill_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('issuer', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('awarded_at', models.DateField()),
            ],
            options={
                'ordering': ['-awarded_at', 'title'],
            },
        ),
    ]
