# Generated by Django 5.2.17 on 2026-09-28 04:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_award'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='starred_by',
            field=models.ManyToManyField(blank=True, related_name='starred_award', to=settings.AUTH_USER_MODEL),
        ),
    ]
